services:
  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: plataforma-veiculos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - laravel
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - laravel
    volumes:
      - mongodata:/data/db

networks:
  laravel:

volumes:
  pgdata:
  mongodata:
